# Generated by Django 5.0.2 on 2024-04-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJIO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_Src', models.CharField(max_length=255)),
                ('Brand_Name', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=255)),
                ('Stars', models.IntegerField()),
                ('Rating', models.CharField(max_length=255)),
                ('Actual_Price', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('Value', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='kidsdata',
            name='Rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mensdata',
            name='Rating',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='womensdata',
            name='Rating',
            field=models.CharField(max_length=255),
        ),
    ]
