# Generated by Django 5.0.2 on 2024-04-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AJIO', '0002_logindata_ordersdata_alter_kidsdata_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersdata',
            name='Order_Id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
